#dev_repo
name: trigger test in another repository
on: workflow_dispatch
jobs:
  trigger-test:
     runs-on: ubuntu-latest
     steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="SachinTharaka" 
          repo_name="selenium"  
          event_type="my-event" 
          service=${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"
       
     
