#dev_repo
name: trigger test in another repository
on: workflow_dispatch
jobs:
  trigger-test:
     runs-on: ubuntu-latest
     steps:
      - name: Trigger Workflow in Another Repository
        uses: actions/checkout@v3
       
       
        with:
          token: ${{ secrets.REPO }}
          repository: SachinTharaka/selenium
          event-type: my-event

      - name: Build with Maven
        run: mvn test
       
     
